#!/bin/bash
# Allocate four Perlmutter GPU nodes, open an interactive shell on one compute
# node, and start the shared 16-GPU Ray cluster. Run this script on a login node.

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"

SALLOC_NODES="${SALLOC_NODES:-4}"
SALLOC_QOS="${SALLOC_QOS:-interactive}"
SALLOC_TIME="${SALLOC_TIME:-04:00:00}"
SALLOC_CONSTRAINT="${SALLOC_CONSTRAINT:-gpu}"
SALLOC_GPUS_PER_NODE="${SALLOC_GPUS_PER_NODE:-4}"
SALLOC_ACCOUNT="${SALLOC_ACCOUNT:-m5019_g}"
SALLOC_IMAGE="${SALLOC_IMAGE:-registry.nersc.gov/m2616/avencast/evenet:1.3}"

export PYTHONPATH="$REPO_ROOT/evenet_dgpo:$REPO_ROOT:${PYTHONPATH:-}"

# salloc/srun inherit exported environment variables. Do not write credentials
# into the generated rcfile.
if [[ -z "${WANDB_API_KEY:-}" ]]; then
    echo "WARNING: WANDB_API_KEY is not set; set it in the interactive shell before training." >&2
fi

INNER_RCFILE="$HOME/.ml_pipeline_salloc_4node_ray_rc"
trap 'rm -f "$INNER_RCFILE"' EXIT

cat > "$INNER_RCFILE" <<EOF
# Generated by ml_pipeline/NERSC/salloc_4node_16gpu_ray.sh.
set +e
[ -f ~/.bashrc ] && { . ~/.bashrc; } 2>/dev/null

cd "$REPO_ROOT" || exit 1
export PYTHONPATH="\$PWD/evenet_dgpo:\$PWD:\${PYTHONPATH:-}"
export RAY_TMPDIR="/tmp/r\${UID}_\${SLURM_JOB_ID:-manual}"
export TORCH_NCCL_TIMEOUT=180

# Ray detects this opt-out by presence/truthiness. Keep it absent for normal
# one-GPU-per-worker assignment; preserve only an explicit truthy override.
case "\${RAY_EXPERIMENTAL_NOSET_CUDA_VISIBLE_DEVICES:-}" in
    ""|0|false|False|no|No|off|Off)
        unset RAY_EXPERIMENTAL_NOSET_CUDA_VISIBLE_DEVICES
        ;;
esac

echo
echo "============================================================"
echo "[ml_pipeline] allocation: \${SLURM_JOB_ID:-?} (\${SLURM_NODELIST:-?})"
echo "[ml_pipeline] repo:       \$PWD"
echo "[ml_pipeline] image:      $SALLOC_IMAGE"
echo "[ml_pipeline] RAY_TMPDIR: \$RAY_TMPDIR"
echo "============================================================"
echo

source NERSC/start_interactive_ray.sh
export RAY_ADDRESS="\$head_node_ip:\$port"

echo
echo "Ray cluster is ready. Expected capacity: 4 active nodes / 16 GPUs."
echo "Check: shifter ray status --address=\$RAY_ADDRESS"
echo "Exit this shell to release the allocation."
echo

PS1='[\u@\h \W]\\$ '
export PS1
EOF

echo "[ml_pipeline] repo: $REPO_ROOT"
echo "[ml_pipeline] requesting ${SALLOC_NODES} nodes x ${SALLOC_GPUS_PER_NODE} GPUs"

salloc \
    --nodes "$SALLOC_NODES" \
    --qos "$SALLOC_QOS" \
    --time "$SALLOC_TIME" \
    --constraint "$SALLOC_CONSTRAINT" \
    --gpus-per-node="$SALLOC_GPUS_PER_NODE" \
    --account "$SALLOC_ACCOUNT" \
    --image="$SALLOC_IMAGE" \
    srun --nodes=1 --ntasks=1 --overlap --pty bash --rcfile "$INNER_RCFILE" -i
