options:
  Training:
    # Stage 1: supervised AD/foundation-style training.
    # Keep model_checkpoint_load_path null unless you explicitly want Lightning resume.
    model_checkpoint_load_path: null
    pretrain_model_load_path: /pscratch/sd/t/tihsu/database/ZtautauAnalysis/ml_baseline_full_analysis/checkpoint-pretrain-cls/last.ckpt
    model_checkpoint_save_path: /pscratch/sd/t/tihsu/database/ZtautauAnalysis/ml_baseline_full_analysis/checkpoint-pretrain-ad

logger:
  wandb:
    run_name: EveNet-AD-Stage
  local:
    name: EveNet-AD-Stage

platform:
  batch_size: 16384