#!/usr/bin/env python3
"""Fixed step260 replay: cold versus full warm start trained to a BCE plateau.

No policy updates, generation, reward installation or production checkpoint writes.
"""
import argparse
from dataclasses import asdict
from functools import partial
import json
import math
import os
from pathlib import Path
import time

import torch
import yaml
import ablate_raw_monitor_initialization as base
from residual_diagnostic_wandb import DiagnosticWandb, validate_wandb

ARMS = ('A_cold', 'C_full_warm')


def settings(value):
    c = base.validate_settings(value)
    c['wandb'] = validate_wandb(c.get('wandb'))
    for key in ('minimum_updates', 'validation_interval', 'patience_evaluations'):
        if type(c[key]) is not int or c[key] < 1:
            raise ValueError(f'Invalid {key}')
    if c['minimum_updates'] >= c['steps']:
        raise ValueError('Safety cap must exceed minimum_updates')
    if not isinstance(c['seeds'], list) or len(c['seeds']) < 2 or len(set(c['seeds'])) != len(c['seeds']):
        raise ValueError('Need at least two distinct seeds')
    if any(type(s) is not int or s < 1 for s in c['seeds']):
        raise ValueError('Seeds must be positive integers')
    return c


def weight_metrics(logits):
    z = logits.detach().double().flatten()
    if not len(z) or not torch.isfinite(z).all():
        raise ValueError('Invalid ratio logits')
    mass = torch.softmax(z, dim=0)
    return {'ess_fraction':float(1/(len(z)*mass.square().sum())),
            'max_mean_one_weight':float(len(z)*mass.max()),
            'top_1pct_mass':float(mass.topk(max(1,math.ceil(.01*len(z)))).values.sum())}


def paired_bce(cold, warm):
    # Pair truth/generated by event identity; preserve within-event correlation.
    def losses(scores):
        return .5*(torch.nn.functional.softplus(-scores['truth_logits'].double())+
                   torch.nn.functional.softplus(scores['raw_logits'].double()))
    delta = losses(cold)-losses(warm)
    mean = float(delta.mean())
    se = float(delta.std(unbiased=True)/math.sqrt(len(delta)))
    return {'cold_minus_warm':mean,'normal_95_low':mean-1.96*se,
            'normal_95_high':mean+1.96*se,'events':len(delta),
            'exploratory_only':'Same validation selected checkpoints; interval is not a selection-corrected test.'}


def run_arm(model, arm, data, cfg, *, rank=0, tracker=None):
    from RL.DGPO_neutrino.omnifold_ztautau.ratio_fit import RatioFitConfig, fit_density_ratio, _broadcast_module
    _broadcast_module(model)
    out = Path(cfg['output_dir'])/arm
    if rank == 0:out.mkdir(exist_ok=False)
    frozen = base.replay.state_digest(base.frozen_state(model))
    prefix = f"restart/seed{cfg['seed']}/{arm}"
    rows = []
    started = time.monotonic()

    def evaluate(step, phase='live'):
        training = model.training
        try:
            metrics,scores = base.replay.score_monitor(model,data['validation_condition'],
                data['validation_truth'],data['validation_raw'],cfg['score_batch_size'])
        finally:model.train(training)
        row = {'step':step, **metrics,'weights':weight_metrics(scores['raw_logits']),
               'elapsed_seconds':time.monotonic()-started}
        if rank == 0:
            base.replay._exclusive_json(out/f'{phase}_{step}.json',row)
            if phase == 'selected':base.replay._exclusive_torch_save(out/'selected_scores.pt',scores)
        if tracker:tracker.emit(prefix+'/'+phase,step,row)
        return row

    rows.append(evaluate(0))
    def progress(row):
        step = int(row['step'])
        if tracker:
            values={'training_loss':row['training_loss']}
            if row.get('validation_evaluated'):values['validation_loss']=row['validation_loss']
            if step % 10 == 0:tracker.emit(prefix+'/fit',step,values)
        if step % cfg['validation_interval'] == 0:
            rows.append(evaluate(step))
            if rank == 0:print(f"[restart] seed={cfg['seed']} arm={arm} step={step} AUC={rows[-1]['auc']:.6f} BCE={rows[-1]['bce']:.6f}",flush=True)
    fc = RatioFitConfig(steps=cfg['steps'],min_steps=cfg['minimum_updates'],
        batch_size=cfg['batch_size'],train_microbatch_size_per_rank=cfg['microbatch_size'],
        sampling='independent_epoch_shuffle',drop_last_batch=True,
        learning_rate=cfg['learning_rate'],weight_decay=cfg['weight_decay'],gradient_clip_norm=cfg['gradient_clip_norm'],
        validation_interval_steps=cfg['validation_interval'],validation_patience_evaluations=cfg['patience_evaluations'],
        validation_min_delta=.0001,validation_batch_size=cfg['score_batch_size'],
        restore_best=True,require_saturation=False,progress_interval_steps=1)
    validation=(data['validation_condition'],data['validation_truth'],torch.ones_like(data['validation_truth'][:,0]),
                data['validation_condition'],data['validation_raw'],torch.ones_like(data['validation_raw'][:,:,0]))
    with base.seeded(cfg['seed'],next(model.parameters()).device):
        diag=fit_density_ratio(model,data['train_condition'],data['train_truth'],torch.ones_like(data['train_truth'][:,0]),
            data['train_condition'],data['train_raw'],torch.ones_like(data['train_raw'][:,:,0]),
            fc,cfg['seed'],validation=validation,progress_callback=progress)
    selected=evaluate(diag.steps_completed,'selected')
    if frozen != base.replay.state_digest(base.frozen_state(model)):raise RuntimeError('Frozen backbone changed')
    result={'arm':arm,'initial':rows[0],'final':selected,'evaluations':rows,
            'saturated':bool(diag.saturated),'steps_completed':diag.steps_completed,
            'elapsed_seconds':time.monotonic()-started,'fit_config':asdict(fc),
            'frozen_backbone_unchanged':True,'cap_hit_without_plateau':not diag.saturated}
    if rank == 0:
        base.replay._exclusive_torch_save(out/'selected_monitor.pt',base.clone_state(model.state_dict()))
        base.replay._exclusive_json(out/'report.json',result)
    return result


def summary(results,cfg):
    a,b=(results[k] for k in ARMS)
    return {'seed':cfg['seed'],'policy_updates':0,'policy_generations':0,
        'both_reached_plateau':a['saturated'] and b['saturated'],
        'cold_minus_warm_bce':a['final']['bce']-b['final']['bce'],
        'cold_minus_warm_auc':a['final']['auc']-b['final']['auc'],
        'arms':{k:{x:r[x] for x in ('final','steps_completed','elapsed_seconds','saturated')} for k,r in results.items()},
        'paired_bce':paired_bce(*(base.tensor_read(Path(cfg['output_dir'])/k/'selected_scores.pt') for k in ARMS))}


def worker(cfg):
    import ray.train
    import ray.train.torch
    rank=ray.train.get_context().get_world_rank()
    tracker=DiagnosticWandb(cfg,rank=rank,device=ray.train.torch.get_device())
    tracker.start()
    try:
        for child in cfg['children']:
            base.ablation_worker(child,run_arm_fn=partial(run_arm,tracker=tracker),summary_fn=summary,arm_names=ARMS)
        if rank == 0:
            reports=[base.json_read(Path(c['output_dir'])/'summary.json') for c in cfg['children']]
            complete=all(r['both_reached_plateau'] for r in reports)
            recommendation=('inconclusive: extend cap for unsaturated arms' if not complete else
                'cold restart is promising; confirm on another policy point' if all(r['cold_minus_warm_bce']<-.002 and r['cold_minus_warm_auc']>=-.005 for r in reports) else
                'no consistent evidence to replace warm-start; inspect per-seed results')
            report={'policy_updates':0,'policy_generations':0,'classifier_fits':2*len(reports),
                    'seeds':reports,'recommendation':recommendation,'limitations':cfg['limitations']}
            base.replay._exclusive_json(Path(cfg['output_dir'])/'summary.json',report)
            base.replay._exclusive_json(Path(cfg['output_dir'])/'report.json',report)
            tracker.emit('restart/summary',len(reports),{'both_reached_plateau':complete})
            print(json.dumps({'recommendation':recommendation}),flush=True)
        tracker.finish(0)
    except BaseException:
        tracker.finish(1)
        raise


def main():
    p=argparse.ArgumentParser(description=__doc__)
    p.add_argument('config',type=Path)
    p.add_argument('--check-only',action='store_true')
    args=p.parse_args()
    cfg,splits=base.prepare(settings(yaml.safe_load(args.config.read_text())))
    cfg['training_seeds']=cfg['seeds'];cfg['expected_policy_step']=260
    cfg['policy_checkpoint']=cfg['paths']['old_checkpoint'];cfg['policy_sha256']=cfg['policy_state_sha256']
    print(f"Verified step260 fixed replay: train={cfg['training_events']} val={cfg['validation_events']}; no policy updates",flush=True)
    if args.check_only:return
    base.create_output(cfg,splits)
    children=[]
    for seed in cfg['seeds']:
        child={**cfg,'seed':seed,'output_dir':str(Path(cfg['output_dir'])/f'seed_{seed}')}
        base.create_output(child,splits);children.append(child)
    cfg['children']=children
    import ray
    from ray.train import RunConfig,ScalingConfig,FailureConfig
    from ray.train.torch import TorchTrainer
    ray.init(address=os.environ.get('RAY_ADDRESS') or 'auto',runtime_env={'env_vars':{
        'PYTHONPATH':os.pathsep.join([str(base.ROOT/'evenet_dgpo'),str(base.ROOT/'scripts'),os.environ.get('PYTHONPATH','')])}})
    TorchTrainer(train_loop_per_worker=worker,train_loop_config=cfg,
        scaling_config=ScalingConfig(num_workers=cfg['workers'],use_gpu=True,resources_per_worker={'CPU':2,'GPU':1}),
        run_config=RunConfig(name='monitor-restart-plateau',storage_path=str(Path(cfg['output_dir'])/'ray_results'),
                             failure_config=FailureConfig(max_failures=0))).fit()


if __name__=='__main__':main()
